name: Events canister - deploy stage
on:
  workflow_dispatch:
    inputs:
      action:
        description: "Type of deploy action"
        required: true
        type: choice
        options:
          - upgrade
          - install
          - reinstall

jobs:
  deploy_stage:
    if: github.ref == 'refs/heads/stage'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: aviate-labs/setup-dfx@v0.2.3
        with:
          dfx-version: 0.9.3
          vessel-version: 0.6.3

      - name: deploy to dfinity mainnet
        run: |
          echo ${CANISTERS_STATE} > state.json
          ./scripts/lib/build_stage.sh
          ./scripts/lib/deploy_stage.sh
        env:
          ACTION: ${{ github.event.inputs.action }}
          CANISTERS_STATE: ${{ secrets.CANISTERS_STATE_STAGE }}
          WALLET_ID: mf5qf-uiaaa-aaaak-qaaja-cai
          ICP_URL: https://mainnet.dfinity.network
          DFX_IDENTITY: ${{ secrets.DFX_IDENTITY_STAGE }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID_STAGE }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET_STAGE }}
          AZURE_KEY_ID: ${{ secrets.AZURE_KEY_ID_STAGE }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID_STAGE }}
          AZURE_VAULT_ID: ${{ secrets.AZURE_VAULT_ID_STAGE }}
