name: Events canister - deploy prod
on:
  workflow_dispatch:
    inputs:
      action:
        description: "Type of deploy action"
        required: true
        type: choice
        options:
          - upgrade
          - install
          - reinstall

jobs:
  deploy_prod:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: aviate-labs/setup-dfx@v0.2.3
        with:
          dfx-version: 0.11.0
          vessel-version: 0.6.3

      - name: deploy to dfinity mainnet
        run: |
          echo ${CANISTERS_STATE} > state.json
          ./scripts/lib/build_prod.sh
          ./scripts/lib/deploy_prod.sh
        env:
          ACTION: ${{ github.event.inputs.action }}
          CANISTERS_STATE: ${{ secrets.CANISTERS_STATE_PROD }}
          WALLET_ID: pan6d-5yaaa-aaaak-aabpa-cai
          ICP_URL: https://mainnet.dfinity.network
          DFX_IDENTITY: ${{ secrets.DFX_IDENTITY_PROD }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID_PROD }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET_PROD }}
          AZURE_KEY_ID: ${{ secrets.AZURE_KEY_ID_PROD }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID_PROD }}
          AZURE_VAULT_ID: ${{ secrets.AZURE_VAULT_ID_PROD }}
